#!/usr/bin/env python3
"""Build the ClawBox brand assets the claw machine embeds.

- The crab mascot's animation rows, cut from the first-party `vibrant-clawd`
  Petdex sheet (8 columns x 9 rows of 192x208 cells) into one small sheet.
- The ClawBox wordmark for the header (the dark-background version).

Both come from ID-Robots/clawbox at a pinned commit, so the output is
reproducible, and are written to src/brand-assets.ts as base64 WebP data URIs,
because camo blocks external image URLs inside a README SVG.

Run from the repo root (needs Python 3 + Pillow):
  npm run build:assets
"""
import base64
import io
import pathlib
import urllib.request

from PIL import Image

SOURCE_SHA = '6b6734a90bfe2fb395b69528ff14223efe5b4408'
SOURCE = f'https://raw.githubusercontent.com/ID-Robots/clawbox/{SOURCE_SHA}'
CELL_W, CELL_H = 192, 208
# Source row per animation we use (CODEX_STATE_ROWS in the clawbox repo).
# Running left is drawn by mirroring runRight, which halves what we embed.
ROWS = {'idle': 0, 'runRight': 1, 'jump': 4, 'failed': 5}
SCALE = 0.42  # ~77 px frames: sharp at 2x on a ~40 px crab, ~63 KB of WebP
QUALITY = 65
WORDMARK_H = 76  # 2x the ~38 px it is drawn at in the header

OUT = pathlib.Path(__file__).resolve().parent.parent / 'src' / 'brand-assets.ts'


def fetch(path: str) -> Image.Image:
    with urllib.request.urlopen(f'{SOURCE}/{path}') as resp:
        return Image.open(io.BytesIO(resp.read())).convert('RGBA')


def webp_uri(img: Image.Image, quality: int) -> tuple[str, int]:
    buf = io.BytesIO()
    img.save(buf, 'WEBP', quality=quality, alpha_quality=70, method=6)
    return 'data:image/webp;base64,' + base64.b64encode(buf.getvalue()).decode(), len(buf.getvalue())


sheet = fetch('public/pets/vibrant-clawd/spritesheet.webp')


def frames_in(row: int) -> list[Image.Image]:
    """The drawn cells of one row; rows are ragged, so empty tail cells are dropped."""
    cells = []
    for col in range(sheet.width // CELL_W):
        cell = sheet.crop((col * CELL_W, row * CELL_H, (col + 1) * CELL_W, (row + 1) * CELL_H))
        if cell.getbbox():
            cells.append(cell)
    return cells


rows = {name: frames_in(row) for name, row in ROWS.items()}

# One crop box shared by every frame, so the crab never jumps between rows.
boxes = [cell.getbbox() for cells in rows.values() for cell in cells]
crop = (min(b[0] for b in boxes), min(b[1] for b in boxes),
        max(b[2] for b in boxes), max(b[3] for b in boxes))
frame_w = round((crop[2] - crop[0]) * SCALE)
frame_h = round((crop[3] - crop[1]) * SCALE)
max_frames = max(len(cells) for cells in rows.values())

out = Image.new('RGBA', (frame_w * max_frames, frame_h * len(rows)))
for r, cells in enumerate(rows.values()):
    for c, cell in enumerate(cells):
        frame = cell.crop(crop).resize((frame_w, frame_h), Image.LANCZOS)
        out.alpha_composite(frame, (c * frame_w, r * frame_h))

data_uri, sheet_bytes = webp_uri(out, QUALITY)

wordmark = fetch('docs-site/logo/dark-wordmark.png')
wordmark = wordmark.crop(wordmark.getbbox())
wordmark = wordmark.resize((round(wordmark.width * WORDMARK_H / wordmark.height), WORDMARK_H), Image.LANCZOS)
wordmark_uri, wordmark_bytes = webp_uri(wordmark, 80)

row_entries = ',\n'.join(
    f"  {name}: {{ row: {r}, frames: {len(cells)} }}" for r, (name, cells) in enumerate(rows.items())
)
OUT.write_text(
    f"""// GENERATED by scripts/build-brand-assets.py — do not edit by hand.
// First-party ClawBox art from ID-Robots/clawbox @ {SOURCE_SHA[:9]}: the crab mascot
// (public/pets/vibrant-clawd), cut to the rows the claw machine uses, and the wordmark.

/** One animation strip: which row of the sheet, and how many frames it draws. */
export interface SpriteRow {{
  row: number;
  frames: number;
}}

export const MASCOT_FRAME_W = {frame_w};
export const MASCOT_FRAME_H = {frame_h};
export const MASCOT_SHEET_W = {out.width};
export const MASCOT_SHEET_H = {out.height};

export const MASCOT_ROWS = {{
{row_entries},
}} as const satisfies Record<string, SpriteRow>;

export type MascotPose = keyof typeof MASCOT_ROWS;

export const MASCOT_SHEET =
  '{data_uri}';

/** The ClawBox wordmark (crab + "ClawBox"), white text for a dark panel. */
export const WORDMARK_W = {wordmark.width};
export const WORDMARK_H = {wordmark.height};
export const WORDMARK =
  '{wordmark_uri}';
""",
    encoding='utf-8',
)
print(f'wrote {OUT}: sheet {sheet_bytes} B ({frame_w}x{frame_h} frames, '
      f'{ {n: len(c) for n, c in rows.items()} }), wordmark {wordmark_bytes} B '
      f'({wordmark.width}x{wordmark.height})')
